package app.bookey.api.club;

import app.bookey.api.book.dto.BookDtos.BookSummary;
import app.bookey.api.club.dto.ClubCommunityDtos.*;
import app.bookey.api.social.WalletService;
import app.bookey.common.error.*;
import app.bookey.domain.book.*;
import app.bookey.domain.club.*;
import app.bookey.domain.user.*;
import app.bookey.domain.wallet.*;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.Instant; import java.util.*; import java.util.function.Function; import java.util.stream.Collectors;

@Service @RequiredArgsConstructor
public class ClubCommunityService {
 private static final int CHAT_COST=2;
 /** 지금 클럽에 없는 사람(나갔거나 내보내졌거나, 다시 참가하기 전의 그 사람)의 채팅 이름. */
 private static final String LEFT_MEMBER_NICKNAME="나간 멤버";
 private final ClubService clubService; private final ClubRepository clubRepository; private final ClubMemberRepository memberRepository; private final ClubChatUnlockRepository unlocks; private final ClubChatMessageRepository messages; private final ClubChatReadRepository reads; private final ClubMeetingRepository meetings; private final ClubMeetingAttendeeRepository attendees; private final UserRepository users; private final WalletService walletService; private final BookRepository books;
 @Transactional(readOnly=true) public ChatState chatState(Long userId,Long clubId){clubService.activeMember(clubId,userId); boolean unlocked=unlocks.existsByClubIdAndUserId(clubId,userId); long total=messages.countByClubId(clubId); Long last=messages.lastId(clubId); long unread=reads.findById(new ClubChatRead.Key(clubId,userId)).map(r->last==null?0:messages.countByClubIdAndIdGreaterThan(clubId,Optional.ofNullable(r.getLastReadMessageId()).orElse(0L))).orElse(total); Instant activity=last==null?null:messages.findById(last).map(ClubChatMessage::getCreatedAt).orElse(null); return new ChatState(unlocked,CHAT_COST,walletService.balance(userId),unread,total,activity);}
 @Transactional public UnlockResult unlock(Long userId,Long clubId){return unlockFor(userId,clubId,userId);}
 @Transactional public UnlockResult giftUnlock(Long payerId,Long clubId,Long targetId){clubService.activeMember(clubId,targetId);return unlockFor(payerId,clubId,targetId);}
 private UnlockResult unlockFor(Long payerId,Long clubId,Long targetId){clubService.activeMember(clubId,payerId); if(unlocks.existsByClubIdAndUserId(clubId,targetId))return new UnlockResult(true,walletService.balance(payerId)); Wallet wallet=walletService.spendBookmarks(payerId,CHAT_COST,WalletTransactionKind.CLUB_CHAT_UNLOCK,"CLUB_CHAT_GIFT",targetId); unlocks.save(new ClubChatUnlock(clubId,targetId,payerId,CHAT_COST)); return new UnlockResult(true,wallet.getBookmarkBalance());}
 @Transactional(readOnly=true) public List<ChatGiftCandidate> giftCandidates(Long userId,Long clubId){clubService.activeMember(clubId,userId);var ms=memberRepository.findAllByClubIdAndStatus(clubId,ClubMemberStatus.ACTIVE);var map=users.findAllById(ms.stream().map(ClubMember::getUserId).toList()).stream().collect(Collectors.toMap(User::getId,User::getNickname));return ms.stream().filter(m->!m.getUserId().equals(userId)).map(m->new ChatGiftCandidate(m.getUserId(),map.get(m.getUserId()),unlocks.existsByClubIdAndUserId(clubId,m.getUserId()))).toList();}
 /** 메시지는 보낸 사람이 지금 ACTIVE 멤버이고 이번 참가(joinedAt) 뒤에 보냈을 때만 그 사람의 것으로 보인다 —
  *  나간 사람의 메시지는 '나간 멤버'가 되고, 다시 참가해도 예전 메시지는 내 것으로 이어지지 않는다. */
 @Transactional public ChatMessagesView chatMessages(Long userId,Long clubId,Long beforeId){requireUnlocked(userId,clubId); var page=PageRequest.of(0,50); var list=beforeId==null?messages.findAllByClubIdOrderByIdDesc(clubId,page):messages.findAllByClubIdAndIdLessThanOrderByIdDesc(clubId,beforeId,page); var senderIds=list.stream().map(ClubChatMessage::getSenderId).distinct().toList(); Map<Long,User> authors=users.findAllById(senderIds).stream().collect(Collectors.toMap(User::getId,Function.identity())); Map<Long,ClubMember> stints=senderIds.isEmpty()?Map.of():memberRepository.findAllByClubIdAndUserIdIn(clubId,senderIds).stream().collect(Collectors.toMap(ClubMember::getUserId,Function.identity())); Long last=messages.lastId(clubId); var key=new ClubChatRead.Key(clubId,userId); reads.findById(key).ifPresentOrElse(r->r.read(last),()->reads.save(new ClubChatRead(clubId,userId,last))); return new ChatMessagesView(list.stream().map(m->chatView(m,authors.get(m.getSenderId()),stints.get(m.getSenderId()),userId)).toList(),list.size()==50?list.get(49).getId():null);}
 private static ChatMessageView chatView(ClubChatMessage m,User author,ClubMember stint,Long userId){boolean present=author!=null&&stint!=null&&stint.getStatus()==ClubMemberStatus.ACTIVE&&m.getCreatedAt()!=null&&!m.getCreatedAt().isBefore(stint.getJoinedAt()); if(!present)return new ChatMessageView(m.getId(),null,LEFT_MEMBER_NICKNAME,m.getBody(),m.getCreatedAt(),false); return new ChatMessageView(m.getId(),m.getSenderId(),author.getNickname(),m.getBody(),m.getCreatedAt(),m.getSenderId().equals(userId));}
 @Transactional public ChatMessageView send(Long userId,Long clubId,SendChatRequest request){requireUnlocked(userId,clubId); if(clubRepository.findById(clubId).orElseThrow(()->ApiException.of(ErrorCode.CLUB_NOT_FOUND)).getStatus().isOver())throw ApiException.of(ErrorCode.CLUB_ENDED); ClubChatMessage m=messages.save(new ClubChatMessage(clubId,userId,request.body().trim())); User u=users.findById(userId).orElseThrow(); reads.save(new ClubChatRead(clubId,userId,m.getId())); return new ChatMessageView(m.getId(),userId,u.getNickname(),m.getBody(),m.getCreatedAt(),true);}
 private void requireUnlocked(Long u,Long c){clubService.activeMember(c,u);if(!unlocks.existsByClubIdAndUserId(c,u))throw ApiException.of(ErrorCode.CLUB_CHAT_LOCKED);}
 @Transactional(readOnly=true) public List<MeetingView> meetingList(Long u,Long c){clubService.activeMember(c,u);return meetings.findAllByClubIdOrderByStartsAtAsc(c).stream().map(m->meetingView(m,u)).toList();}
 @Transactional(readOnly=true) public MeetingView meetingDetail(Long u,Long c,Long id){clubService.activeMember(c,u);return meetingView(meeting(c,id),u);}
 /** 만남을 열고 · 고치고 · 취소하면 다가오는 만남의 책이 달라질 수 있어 모임의 지금 읽는 책을 다시 맞춘다.
  *  만남은 멤버 누구나 연다. 연 사람은 처음부터 참여자다(빠질 수 없다). 고치고 취소하는 건 연 사람과 호스트만. */
 @Transactional public MeetingView createMeeting(Long u,Long c,UpsertMeetingRequest r){clubService.activeMember(c,u);validateMeeting(r);ClubMeeting m=meetings.save(new ClubMeeting(c,u,r.title(),r.description(),r.startsAt(),r.endsAt(),r.placeName(),r.address(),r.latitude(),r.longitude(),r.mapUrl(),r.responseDeadline(),r.bookId(),r.maxAttendees()));attendees.save(new ClubMeetingAttendee(m.getId(),u));clubService.syncCurrentBook(c);return meetingView(m,u);}
 @Transactional public MeetingView updateMeeting(Long u,Long c,Long id,UpsertMeetingRequest r){ClubMeeting m=organizedMeeting(u,c,id);validateMeeting(r);if(!m.isOpen())throw ApiException.of(ErrorCode.INVALID_REQUEST);if(r.maxAttendees()!=null&&attendees.countByMeetingId(id)>r.maxAttendees())throw new ApiException(ErrorCode.INVALID_REQUEST,"이미 참여한 사람보다 적게 줄일 수 없어요.");m.update(r.title(),r.description(),r.startsAt(),r.endsAt(),r.placeName(),r.address(),r.latitude(),r.longitude(),r.mapUrl(),r.responseDeadline(),r.bookId(),r.maxAttendees());clubService.syncCurrentBook(c);return meetingView(m,u);}
 @Transactional public void cancelMeeting(Long u,Long c,Long id){ClubMeeting m=organizedMeeting(u,c,id);m.cancel();clubService.syncCurrentBook(c);}
 /** 참여 — 모임 행을 잠근 뒤 정원을 본다. 이미 참여 중이면 그대로 돌려준다(다시 눌러도 같다). */
 @Transactional public MeetingView attend(Long u,Long c,Long id){clubService.activeMember(c,u);meeting(c,id);ClubMeeting m=meetings.findByIdForUpdate(id).orElseThrow(()->ApiException.of(ErrorCode.CLUB_MEETING_NOT_FOUND));if(!m.isOpen()||(m.getResponseDeadline()!=null&&m.getResponseDeadline().isBefore(Instant.now())))throw ApiException.of(ErrorCode.INVALID_REQUEST);var key=new ClubMeetingAttendee.Key(id,u);if(!attendees.existsById(key)){if(m.isFull(attendees.countByMeetingId(id)))throw ApiException.of(ErrorCode.MEETING_FULL);attendees.save(new ClubMeetingAttendee(id,u));}return meetingView(m,u);}
 /** 참여 취소 — 모임을 연 사람은 빠질 수 없다. 못 가게 되면 모임을 취소한다. */
 @Transactional public MeetingView unattend(Long u,Long c,Long id){clubService.activeMember(c,u);ClubMeeting m=meeting(c,id);if(Objects.equals(m.getCreatedBy(),u))throw new ApiException(ErrorCode.INVALID_REQUEST,"모임을 연 사람은 참여를 취소할 수 없어요. 못 가게 되면 모임을 취소해 주세요.");attendees.deleteById(new ClubMeetingAttendee.Key(id,u));return meetingView(m,u);}
 /** 고치거나 취소할 만남 — 그 만남을 연 멤버나 클럽 호스트만 받는다. */
 private ClubMeeting organizedMeeting(Long u,Long c,Long id){ClubMember me=clubService.activeMember(c,u);ClubMeeting m=meeting(c,id);if(!Objects.equals(m.getCreatedBy(),u)&&!me.getRole().canManageClub())throw new ApiException(ErrorCode.CLUB_NOT_HOST,"모임을 연 사람과 호스트만 할 수 있어요.");return m;}
 private ClubMeeting meeting(Long c,Long id){ClubMeeting m=meetings.findById(id).orElseThrow(()->ApiException.of(ErrorCode.CLUB_MEETING_NOT_FOUND));if(!m.getClubId().equals(c))throw ApiException.of(ErrorCode.CLUB_MEETING_NOT_FOUND);return m;}
 private void validateMeeting(UpsertMeetingRequest r){if(r.endsAt()!=null&&!r.endsAt().isAfter(r.startsAt()))throw new ApiException(ErrorCode.INVALID_REQUEST,"끝나는 시간은 시작 시간보다 늦어야 해요.");if(r.responseDeadline()!=null&&r.responseDeadline().isAfter(r.startsAt()))throw new ApiException(ErrorCode.INVALID_REQUEST,"참여 응답 마감은 모임 시작 전이어야 해요.");if(r.bookId()!=null&&!books.existsById(r.bookId()))throw ApiException.of(ErrorCode.BOOK_NOT_FOUND);}
 /** 참여한 사람 — 탈퇴한(계정이 종료된) 사람은 이름도 수도 빼고 보여 준다. */
 private MeetingView meetingView(ClubMeeting m,Long u){var list=attendees.findAllByMeetingId(m.getId());var ids=list.stream().map(ClubMeetingAttendee::getUserId).toList();var userMap=users.findAllById(ids).stream().collect(Collectors.toMap(User::getId,Function.identity()));var people=ids.stream().map(userMap::get).filter(x->x!=null&&x.getStatus()!=UserStatus.TERMINATED).map(x->new MeetingAttendeeView(x.getId(),x.getNickname(),x.getAvatarUrl())).toList();var names=people.stream().map(MeetingAttendeeView::nickname).toList();return new MeetingView(m.getId(),m.getClubId(),m.getTitle(),m.getDescription(),m.getStartsAt(),m.getEndsAt(),m.getPlaceName(),m.getAddress(),m.getLatitude(),m.getLongitude(),m.getMapUrl(),m.getResponseDeadline(),m.getStatus(),people.size(),ids.contains(u),Objects.equals(m.getCreatedBy(),u),names,people,m.getBookId()==null?null:books.findById(m.getBookId()).map(BookSummary::from).orElse(null),m.getMaxAttendees());}
}
